"""Demo data generator for AgroFlow Intelligence.

Generates realistic Michoacan agricultural supply chain data.
"""

from __future__ import annotations

from .models import (
    BuyerMatch,
    CertificationType,
    CropType,
    DemoStats,
    ExportDocument,
    Farm,
    Harvest,
    MarketPrice,
    QualityInspection,
    Shipment,
    SupplyChainInsight,
    TempReading,
    WeatherAlert,
)
from . import store


def generate_demo_data() -> None:
    """Generate and persist a complete, interconnected demo dataset."""

    # ── Farms (12) ──────────────────────────────────────────────
    farms = [
        Farm(id="farm-001", name="Rancho Los Aguacates", location_lat=19.4181, location_lng=-102.0534,
             crop_type=CropType.avocado, hectares=65, owner="Juan Carlos Mendoza",
             contact="+52 452 123 4567", created_at="2024-03-15T10:00:00"),
        Farm(id="farm-002", name="Huerta El Paraiso", location_lat=19.3467, location_lng=-102.2256,
             crop_type=CropType.avocado, hectares=42, owner="Maria Elena Gutierrez",
             contact="+52 452 234 5678", created_at="2023-11-20T08:00:00"),
        Farm(id="farm-003", name="Finca San Miguel", location_lat=19.5012, location_lng=-102.0678,
             crop_type=CropType.avocado, hectares=55, owner="Roberto Alvarez Perez",
             contact="+52 452 345 6789", created_at="2024-01-10T09:30:00"),
        Farm(id="farm-004", name="Rancho La Esperanza", location_lat=19.3789, location_lng=-102.1345,
             crop_type=CropType.avocado, hectares=38, owner="Ana Patricia Ramirez",
             contact="+52 452 456 7890", created_at="2024-06-05T11:00:00"),
        Farm(id="farm-005", name="Huerta Don Sergio", location_lat=19.2901, location_lng=-102.3012,
             crop_type=CropType.avocado, hectares=28, owner="Sergio Hernandez Luna",
             contact="+52 452 567 8901", created_at="2025-02-14T07:45:00"),
        Farm(id="farm-006", name="Aguacates del Valle", location_lat=19.4567, location_lng=-102.1890,
             crop_type=CropType.avocado, hectares=50, owner="Fernando Castillo Ortiz",
             contact="+52 452 678 9012", created_at="2024-08-22T10:15:00"),
        Farm(id="farm-007", name="Finca Tancitaro Gold", location_lat=19.3456, location_lng=-102.3567,
             crop_type=CropType.avocado, hectares=72, owner="Luis Miguel Torres",
             contact="+52 452 789 0123", created_at="2023-05-30T08:00:00"),
        Farm(id="farm-008", name="Rancho Verde Periban", location_lat=19.5134, location_lng=-102.4012,
             crop_type=CropType.avocado, hectares=35, owner="Carmen Diaz Flores",
             contact="+52 452 890 1234", created_at="2024-11-01T09:00:00"),
        Farm(id="farm-009", name="Berries Los Reyes", location_lat=19.5823, location_lng=-102.4734,
             crop_type=CropType.berry, hectares=22, owner="Patricia Morales Vega",
             contact="+52 354 123 4567", created_at="2024-04-18T10:30:00"),
        Farm(id="farm-010", name="Frutillas del Sur", location_lat=19.5567, location_lng=-102.5001,
             crop_type=CropType.berry, hectares=18, owner="Jorge Navarro Cruz",
             contact="+52 354 234 5678", created_at="2025-01-08T08:15:00"),
        Farm(id="farm-011", name="Berry Paradise Tacambaro", location_lat=19.2345, location_lng=-101.4567,
             crop_type=CropType.berry, hectares=15, owner="Isabel Dominguez Ramos",
             contact="+52 459 345 6789", created_at="2024-09-12T11:45:00"),
        Farm(id="farm-012", name="Citricos Ario", location_lat=19.2012, location_lng=-101.7234,
             crop_type=CropType.lemon, hectares=10, owner="Ricardo Soto Jimenez",
             contact="+52 459 456 7890", created_at="2025-03-01T07:30:00"),
    ]

    # ── Harvests (30) ──────────────────────────────────────────
    harvests = [
        # Avocado harvests (farm-001 to farm-008)
        Harvest(id="harv-001", farm_id="farm-001", crop_type=CropType.avocado,
                quantity_kg=58500, quality_grade="A", harvest_date="2026-03-01", estimated_value_usd=175500),
        Harvest(id="harv-002", farm_id="farm-001", crop_type=CropType.avocado,
                quantity_kg=52000, quality_grade="A", harvest_date="2026-03-15", estimated_value_usd=156000),
        Harvest(id="harv-003", farm_id="farm-002", crop_type=CropType.avocado,
                quantity_kg=37800, quality_grade="A", harvest_date="2026-03-05", estimated_value_usd=113400),
        Harvest(id="harv-004", farm_id="farm-002", crop_type=CropType.avocado,
                quantity_kg=33600, quality_grade="B", harvest_date="2026-03-20", estimated_value_usd=84000),
        Harvest(id="harv-005", farm_id="farm-003", crop_type=CropType.avocado,
                quantity_kg=49500, quality_grade="A", harvest_date="2026-02-28", estimated_value_usd=148500),
        Harvest(id="harv-006", farm_id="farm-003", crop_type=CropType.avocado,
                quantity_kg=44000, quality_grade="B", harvest_date="2026-03-18", estimated_value_usd=110000),
        Harvest(id="harv-007", farm_id="farm-004", crop_type=CropType.avocado,
                quantity_kg=34200, quality_grade="A", harvest_date="2026-03-02", estimated_value_usd=102600),
        Harvest(id="harv-008", farm_id="farm-004", crop_type=CropType.avocado,
                quantity_kg=30400, quality_grade="B", harvest_date="2026-03-22", estimated_value_usd=76000),
        Harvest(id="harv-009", farm_id="farm-005", crop_type=CropType.avocado,
                quantity_kg=22400, quality_grade="A", harvest_date="2026-03-08", estimated_value_usd=67200),
        Harvest(id="harv-010", farm_id="farm-005", crop_type=CropType.avocado,
                quantity_kg=19600, quality_grade="C", harvest_date="2026-03-25", estimated_value_usd=39200),
        Harvest(id="harv-011", farm_id="farm-006", crop_type=CropType.avocado,
                quantity_kg=45000, quality_grade="A", harvest_date="2026-03-03", estimated_value_usd=135000),
        Harvest(id="harv-012", farm_id="farm-006", crop_type=CropType.avocado,
                quantity_kg=40000, quality_grade="A", harvest_date="2026-03-19", estimated_value_usd=120000),
        Harvest(id="harv-013", farm_id="farm-007", crop_type=CropType.avocado,
                quantity_kg=64800, quality_grade="A", harvest_date="2026-02-25", estimated_value_usd=194400),
        Harvest(id="harv-014", farm_id="farm-007", crop_type=CropType.avocado,
                quantity_kg=57600, quality_grade="A", harvest_date="2026-03-12", estimated_value_usd=172800),
        Harvest(id="harv-015", farm_id="farm-007", crop_type=CropType.avocado,
                quantity_kg=50400, quality_grade="B", harvest_date="2026-03-28", estimated_value_usd=126000),
        Harvest(id="harv-016", farm_id="farm-008", crop_type=CropType.avocado,
                quantity_kg=31500, quality_grade="A", harvest_date="2026-03-06", estimated_value_usd=94500),
        Harvest(id="harv-017", farm_id="farm-008", crop_type=CropType.avocado,
                quantity_kg=28000, quality_grade="B", harvest_date="2026-03-24", estimated_value_usd=70000),
        # Berry harvests (farm-009, farm-010, farm-011)
        Harvest(id="harv-018", farm_id="farm-009", crop_type=CropType.berry,
                quantity_kg=39600, quality_grade="A", harvest_date="2026-03-01", estimated_value_usd=198000),
        Harvest(id="harv-019", farm_id="farm-009", crop_type=CropType.berry,
                quantity_kg=35200, quality_grade="A", harvest_date="2026-03-14", estimated_value_usd=176000),
        Harvest(id="harv-020", farm_id="farm-009", crop_type=CropType.berry,
                quantity_kg=33000, quality_grade="B", harvest_date="2026-03-28", estimated_value_usd=148500),
        Harvest(id="harv-021", farm_id="farm-010", crop_type=CropType.berry,
                quantity_kg=32400, quality_grade="A", harvest_date="2026-03-04", estimated_value_usd=162000),
        Harvest(id="harv-022", farm_id="farm-010", crop_type=CropType.berry,
                quantity_kg=27000, quality_grade="A", harvest_date="2026-03-18", estimated_value_usd=135000),
        Harvest(id="harv-023", farm_id="farm-010", crop_type=CropType.berry,
                quantity_kg=25200, quality_grade="B", harvest_date="2026-03-30", estimated_value_usd=113400),
        Harvest(id="harv-024", farm_id="farm-011", crop_type=CropType.berry,
                quantity_kg=27000, quality_grade="A", harvest_date="2026-03-07", estimated_value_usd=135000),
        Harvest(id="harv-025", farm_id="farm-011", crop_type=CropType.berry,
                quantity_kg=22500, quality_grade="A", harvest_date="2026-03-21", estimated_value_usd=112500),
        Harvest(id="harv-026", farm_id="farm-011", crop_type=CropType.berry,
                quantity_kg=18000, quality_grade="C", harvest_date="2026-04-01", estimated_value_usd=72000),
        # Lemon harvests (farm-012)
        Harvest(id="harv-027", farm_id="farm-012", crop_type=CropType.lemon,
                quantity_kg=12000, quality_grade="A", harvest_date="2026-03-10", estimated_value_usd=18000),
        Harvest(id="harv-028", farm_id="farm-012", crop_type=CropType.lemon,
                quantity_kg=10800, quality_grade="A", harvest_date="2026-03-22", estimated_value_usd=16200),
        Harvest(id="harv-029", farm_id="farm-012", crop_type=CropType.lemon,
                quantity_kg=9600, quality_grade="B", harvest_date="2026-03-31", estimated_value_usd=12480),
        Harvest(id="harv-030", farm_id="farm-012", crop_type=CropType.lemon,
                quantity_kg=8400, quality_grade="B", harvest_date="2026-04-02", estimated_value_usd=10920),
    ]

    # ── Shipments (8) ──────────────────────────────────────────
    shipments = [
        Shipment(
            id="ship-001", harvest_ids=["harv-001", "harv-003", "harv-005"],
            destination="US", status="in_transit", carrier="Maersk",
            container_id="MSKU-7234561", departure_date="2026-03-20", eta="2026-04-08",
            temperature_logs=[
                TempReading(timestamp="2026-03-20T08:00:00", temperature_c=4.2, location="Lazaro Cardenas Port"),
                TempReading(timestamp="2026-03-22T14:00:00", temperature_c=4.5, location="Pacific Ocean"),
                TempReading(timestamp="2026-03-25T06:00:00", temperature_c=4.1, location="Approaching LA"),
                TempReading(timestamp="2026-03-28T10:00:00", temperature_c=4.3, location="Long Beach Port"),
            ],
            documents=["doc-001", "doc-002", "doc-003"],
        ),
        Shipment(
            id="ship-002", harvest_ids=["harv-007", "harv-011"],
            destination="US", status="in_transit", carrier="MSC",
            container_id="MSCU-4891023", departure_date="2026-03-22", eta="2026-04-10",
            temperature_logs=[
                TempReading(timestamp="2026-03-22T10:00:00", temperature_c=4.0, location="Lazaro Cardenas Port"),
                TempReading(timestamp="2026-03-25T12:00:00", temperature_c=4.3, location="Pacific Ocean"),
                TempReading(timestamp="2026-03-28T08:00:00", temperature_c=4.1, location="En route San Diego"),
            ],
            documents=["doc-004", "doc-005"],
        ),
        Shipment(
            id="ship-003", harvest_ids=["harv-013", "harv-014"],
            destination="US", status="customs", carrier="Hapag-Lloyd",
            container_id="HLCU-3456789", departure_date="2026-03-15", eta="2026-04-05",
            temperature_logs=[
                TempReading(timestamp="2026-03-15T06:00:00", temperature_c=3.9, location="Lazaro Cardenas Port"),
                TempReading(timestamp="2026-03-18T14:00:00", temperature_c=4.2, location="Pacific Ocean"),
                TempReading(timestamp="2026-03-22T08:00:00", temperature_c=4.0, location="Near Houston"),
                TempReading(timestamp="2026-03-25T16:00:00", temperature_c=4.4, location="Houston Port"),
                TempReading(timestamp="2026-03-28T10:00:00", temperature_c=4.1, location="US Customs Houston"),
            ],
            documents=["doc-006", "doc-007"],
        ),
        Shipment(
            id="ship-004", harvest_ids=["harv-016", "harv-009"],
            destination="US", status="preparing", carrier="Maersk",
            container_id="MSKU-8901234", departure_date="2026-04-05", eta="2026-04-22",
            temperature_logs=[],
            documents=["doc-008"],
        ),
        Shipment(
            id="ship-005", harvest_ids=["harv-002", "harv-012"],
            destination="US", status="in_transit", carrier="MSC",
            container_id="MSCU-5678901", departure_date="2026-03-25", eta="2026-04-12",
            temperature_logs=[
                TempReading(timestamp="2026-03-25T09:00:00", temperature_c=4.1, location="Lazaro Cardenas Port"),
                TempReading(timestamp="2026-03-28T15:00:00", temperature_c=4.4, location="Pacific Ocean"),
            ],
            documents=["doc-009"],
        ),
        Shipment(
            id="ship-006", harvest_ids=["harv-018", "harv-021"],
            destination="EU", status="in_transit", carrier="Hapag-Lloyd",
            container_id="HLCU-6789012", departure_date="2026-03-18", eta="2026-04-15",
            temperature_logs=[
                TempReading(timestamp="2026-03-18T07:00:00", temperature_c=2.1, location="Lazaro Cardenas Port"),
                TempReading(timestamp="2026-03-22T12:00:00", temperature_c=2.3, location="Atlantic Ocean"),
                TempReading(timestamp="2026-03-26T10:00:00", temperature_c=2.0, location="Mid-Atlantic"),
                TempReading(timestamp="2026-03-30T08:00:00", temperature_c=2.2, location="Approaching Rotterdam"),
            ],
            documents=["doc-010", "doc-011"],
        ),
        Shipment(
            id="ship-007", harvest_ids=["harv-019", "harv-024"],
            destination="EU", status="preparing", carrier="Maersk",
            container_id="MSKU-2345678", departure_date="2026-04-08", eta="2026-05-02",
            temperature_logs=[],
            documents=["doc-012"],
        ),
        Shipment(
            id="ship-008", harvest_ids=["harv-022", "harv-027"],
            destination="Asia", status="in_transit", carrier="MSC",
            container_id="MSCU-9012345", departure_date="2026-03-20", eta="2026-04-18",
            temperature_logs=[
                TempReading(timestamp="2026-03-20T06:00:00", temperature_c=3.0, location="Lazaro Cardenas Port"),
                TempReading(timestamp="2026-03-24T14:00:00", temperature_c=3.2, location="Pacific Ocean"),
                TempReading(timestamp="2026-03-28T10:00:00", temperature_c=3.1, location="Mid-Pacific"),
            ],
            documents=[],
        ),
    ]

    # ── Buyer Matches (6) ──────────────────────────────────────
    buyer_matches = [
        BuyerMatch(id="buyer-001", buyer_name="Costco Wholesale", country="US",
                   crop_interest=CropType.avocado, volume_needed_kg=200000,
                   price_per_kg_usd=3.20,
                   certification_required=[CertificationType.global_gap],
                   matched_farms=["farm-001", "farm-003", "farm-007"]),
        BuyerMatch(id="buyer-002", buyer_name="Walmart Mexico", country="Mexico",
                   crop_interest=CropType.avocado, volume_needed_kg=150000,
                   price_per_kg_usd=2.80,
                   certification_required=[],
                   matched_farms=["farm-002", "farm-004", "farm-005"]),
        BuyerMatch(id="buyer-003", buyer_name="Aldi Europe", country="Germany",
                   crop_interest=CropType.avocado, volume_needed_kg=120000,
                   price_per_kg_usd=3.50,
                   certification_required=[CertificationType.organic, CertificationType.global_gap],
                   matched_farms=["farm-006", "farm-008"]),
        BuyerMatch(id="buyer-004", buyer_name="Fresh Del Monte", country="US",
                   crop_interest=CropType.avocado, volume_needed_kg=180000,
                   price_per_kg_usd=3.10,
                   certification_required=[CertificationType.global_gap],
                   matched_farms=["farm-001", "farm-007"]),
        BuyerMatch(id="buyer-005", buyer_name="Driscoll's", country="US",
                   crop_interest=CropType.berry, volume_needed_kg=90000,
                   price_per_kg_usd=5.50,
                   certification_required=[CertificationType.global_gap, CertificationType.fair_trade],
                   matched_farms=["farm-009", "farm-010", "farm-011"]),
        BuyerMatch(id="buyer-006", buyer_name="Aeon Japan", country="Japan",
                   crop_interest=CropType.berry, volume_needed_kg=45000,
                   price_per_kg_usd=6.00,
                   certification_required=[CertificationType.organic],
                   matched_farms=["farm-009", "farm-010"]),
    ]

    # ── Weather Alerts (5) ─────────────────────────────────────
    weather_alerts = [
        WeatherAlert(id="wx-001", region="Uruapan", alert_type="frost",
                     severity="high", forecast_date="2026-04-06",
                     description="Frost warning: temperatures expected to drop to -2C overnight in the Uruapan valley. Protect young avocado trees and recently pollinated fruit.",
                     affected_farms=["farm-001", "farm-006"]),
        WeatherAlert(id="wx-002", region="Tancitaro", alert_type="rain",
                     severity="medium", forecast_date="2026-04-05",
                     description="Heavy rainfall expected (40-60mm) over the next 48 hours. Potential harvest delays and road access issues on mountain routes.",
                     affected_farms=["farm-007", "farm-008"]),
        WeatherAlert(id="wx-003", region="Los Reyes", alert_type="heat",
                     severity="high", forecast_date="2026-04-07",
                     description="Heat stress alert: daytime temperatures reaching 38C. Berry crops at risk of sunburn and accelerated ripening. Increase irrigation frequency.",
                     affected_farms=["farm-009", "farm-010"]),
        WeatherAlert(id="wx-004", region="Periban", alert_type="wind",
                     severity="low", forecast_date="2026-04-08",
                     description="Moderate winds (30-45 km/h) forecast. Minimal impact expected but secure loose greenhouse covers and irrigation equipment.",
                     affected_farms=["farm-008"]),
        WeatherAlert(id="wx-005", region="Tacambaro", alert_type="rain",
                     severity="critical", forecast_date="2026-04-04",
                     description="Tropical storm remnants bringing 80-100mm rainfall. Flash flood risk in low-lying berry fields. Harvest immediately if possible.",
                     affected_farms=["farm-011"]),
    ]

    # ── Market Prices ──────────────────────────────────────────
    market_prices = [
        MarketPrice(crop_type=CropType.avocado, market="US", price_per_kg_usd=3.20,
                    trend="up", date="2026-04-04", source="USDA Market News"),
        MarketPrice(crop_type=CropType.avocado, market="US (organic)", price_per_kg_usd=3.50,
                    trend="up", date="2026-04-04", source="USDA Market News"),
        MarketPrice(crop_type=CropType.avocado, market="EU", price_per_kg_usd=3.60,
                    trend="stable", date="2026-04-04", source="Eurostat Agri"),
        MarketPrice(crop_type=CropType.avocado, market="domestic", price_per_kg_usd=2.80,
                    trend="down", date="2026-04-04", source="SNIIM Mexico"),
        MarketPrice(crop_type=CropType.berry, market="US", price_per_kg_usd=5.50,
                    trend="up", date="2026-04-04", source="USDA Market News"),
        MarketPrice(crop_type=CropType.berry, market="EU", price_per_kg_usd=6.00,
                    trend="up", date="2026-04-04", source="Eurostat Agri"),
        MarketPrice(crop_type=CropType.berry, market="Asia", price_per_kg_usd=5.80,
                    trend="stable", date="2026-04-04", source="Tokyo Wholesale Market"),
        MarketPrice(crop_type=CropType.lemon, market="US", price_per_kg_usd=1.50,
                    trend="stable", date="2026-04-04", source="USDA Market News"),
        MarketPrice(crop_type=CropType.lemon, market="domestic", price_per_kg_usd=1.20,
                    trend="down", date="2026-04-04", source="SNIIM Mexico"),
    ]

    # ── Quality Inspections (10) ───────────────────────────────
    quality_inspections = [
        QualityInspection(id="qi-001", harvest_id="harv-001", inspector="Ing. Carlos Reyes",
                          ph_level=6.2, brix_level=8.5, defect_pct=1.2,
                          pesticide_residue=False, certification_status="GlobalG.A.P. Certified",
                          inspection_date="2026-03-02"),
        QualityInspection(id="qi-002", harvest_id="harv-003", inspector="Ing. Laura Medina",
                          ph_level=6.0, brix_level=9.1, defect_pct=2.1,
                          pesticide_residue=False, certification_status="GlobalG.A.P. Certified",
                          inspection_date="2026-03-06"),
        QualityInspection(id="qi-003", harvest_id="harv-005", inspector="Ing. Carlos Reyes",
                          ph_level=5.8, brix_level=8.8, defect_pct=1.5,
                          pesticide_residue=False, certification_status="Organic + GlobalG.A.P.",
                          inspection_date="2026-03-01"),
        QualityInspection(id="qi-004", harvest_id="harv-013", inspector="Ing. Miguel Sanchez",
                          ph_level=6.1, brix_level=9.3, defect_pct=0.8,
                          pesticide_residue=False, certification_status="GlobalG.A.P. Certified",
                          inspection_date="2026-02-26"),
        QualityInspection(id="qi-005", harvest_id="harv-010", inspector="Ing. Laura Medina",
                          ph_level=6.5, brix_level=7.2, defect_pct=7.5,
                          pesticide_residue=False, certification_status="Grade C — domestic only",
                          inspection_date="2026-03-26"),
        QualityInspection(id="qi-006", harvest_id="harv-018", inspector="Ing. Sofia Vargas",
                          ph_level=3.4, brix_level=12.5, defect_pct=2.0,
                          pesticide_residue=False, certification_status="GlobalG.A.P. + Fair Trade",
                          inspection_date="2026-03-02"),
        QualityInspection(id="qi-007", harvest_id="harv-021", inspector="Ing. Sofia Vargas",
                          ph_level=3.2, brix_level=13.1, defect_pct=1.8,
                          pesticide_residue=False, certification_status="GlobalG.A.P. Certified",
                          inspection_date="2026-03-05"),
        QualityInspection(id="qi-008", harvest_id="harv-024", inspector="Ing. Laura Medina",
                          ph_level=3.5, brix_level=11.8, defect_pct=3.2,
                          pesticide_residue=False, certification_status="Organic Certified",
                          inspection_date="2026-03-08"),
        QualityInspection(id="qi-009", harvest_id="harv-027", inspector="Ing. Miguel Sanchez",
                          ph_level=2.3, brix_level=7.0, defect_pct=4.5,
                          pesticide_residue=False, certification_status="Pending inspection",
                          inspection_date="2026-03-11"),
        QualityInspection(id="qi-010", harvest_id="harv-026", inspector="Ing. Sofia Vargas",
                          ph_level=3.8, brix_level=10.2, defect_pct=8.0,
                          pesticide_residue=True, certification_status="REJECTED — residue detected",
                          inspection_date="2026-04-02"),
    ]

    # ── Export Documents (12) ──────────────────────────────────
    export_documents = [
        ExportDocument(id="doc-001", shipment_id="ship-001", doc_type="phytosanitary",
                       status="approved", issued_date="2026-03-18", expiry_date="2026-06-18"),
        ExportDocument(id="doc-002", shipment_id="ship-001", doc_type="customs",
                       status="approved", issued_date="2026-03-19", expiry_date="2026-04-19"),
        ExportDocument(id="doc-003", shipment_id="ship-001", doc_type="origin",
                       status="approved", issued_date="2026-03-18", expiry_date="2026-09-18"),
        ExportDocument(id="doc-004", shipment_id="ship-002", doc_type="phytosanitary",
                       status="approved", issued_date="2026-03-20", expiry_date="2026-06-20"),
        ExportDocument(id="doc-005", shipment_id="ship-002", doc_type="customs",
                       status="approved", issued_date="2026-03-21", expiry_date="2026-04-21"),
        ExportDocument(id="doc-006", shipment_id="ship-003", doc_type="phytosanitary",
                       status="approved", issued_date="2026-03-13", expiry_date="2026-06-13"),
        ExportDocument(id="doc-007", shipment_id="ship-003", doc_type="customs",
                       status="pending", issued_date="2026-03-14", expiry_date="2026-04-14"),
        ExportDocument(id="doc-008", shipment_id="ship-004", doc_type="phytosanitary",
                       status="pending", issued_date="2026-04-02", expiry_date="2026-07-02"),
        ExportDocument(id="doc-009", shipment_id="ship-005", doc_type="phytosanitary",
                       status="approved", issued_date="2026-03-23", expiry_date="2026-06-23"),
        ExportDocument(id="doc-010", shipment_id="ship-006", doc_type="phytosanitary",
                       status="approved", issued_date="2026-03-16", expiry_date="2026-06-16"),
        ExportDocument(id="doc-011", shipment_id="ship-006", doc_type="invoice",
                       status="approved", issued_date="2026-03-17", expiry_date="2026-04-17"),
        ExportDocument(id="doc-012", shipment_id="ship-007", doc_type="phytosanitary",
                       status="pending", issued_date="2026-04-03", expiry_date="2026-07-03"),
    ]

    # ── Supply Chain Insights (8) ──────────────────────────────
    insights = [
        SupplyChainInsight(
            id="ins-001", insight_type="optimization", priority="high",
            title="Consolidate Uruapan shipments to reduce per-container cost",
            description="Farms 001 and 006 in the Uruapan region are shipping separately to the US. Consolidating into shared containers could save $8,200/month in freight costs while maintaining cold chain integrity.",
            affected_entities=["farm-001", "farm-006", "ship-001", "ship-005"],
            created_at="2026-04-03T09:00:00"),
        SupplyChainInsight(
            id="ins-002", insight_type="risk", priority="critical",
            title="Frost risk threatens 30% of avocado harvest in Uruapan valley",
            description="Weather models predict unusual frost event April 6-8. Farms 001 and 006 should activate frost protection (wind machines, smudge pots). Estimated loss without action: $85,000 in damaged fruit.",
            affected_entities=["farm-001", "farm-006", "wx-001"],
            created_at="2026-04-03T10:30:00"),
        SupplyChainInsight(
            id="ins-003", insight_type="opportunity", priority="high",
            title="EU organic avocado premium at 5-year high",
            description="EU organic avocado prices hit EUR 3.80/kg. Farms with organic certification (003, 006) should prioritize EU shipments. Potential revenue uplift of $45,000/month by redirecting 20% of US volume to EU.",
            affected_entities=["farm-003", "farm-006", "buyer-003"],
            created_at="2026-04-02T14:00:00"),
        SupplyChainInsight(
            id="ins-004", insight_type="risk", priority="high",
            title="Shipment SHIP-003 customs delay — documents incomplete",
            description="Customs declaration for shipment to Houston is still pending (doc-007). Average clearance takes 3 days; current delay risks $12,000 in demurrage charges. Expedite document submission immediately.",
            affected_entities=["ship-003", "doc-007"],
            created_at="2026-04-03T11:00:00"),
        SupplyChainInsight(
            id="ins-005", insight_type="optimization", priority="medium",
            title="Berry cold chain optimization — lower temperature by 0.5C",
            description="Temperature logs for berry shipments (ship-006) show average 2.15C. Research suggests lowering to 1.5C extends shelf life by 2 days, reducing spoilage losses by an estimated 4%.",
            affected_entities=["ship-006", "farm-009", "farm-010"],
            created_at="2026-04-02T16:00:00"),
        SupplyChainInsight(
            id="ins-006", insight_type="opportunity", priority="medium",
            title="Driscoll's volume increase available for Q2",
            description="Driscoll's buyer contact indicated willingness to increase Q2 berry orders by 25% (additional 22,500 kg). Farms 009-011 have capacity if weather cooperates. Estimated additional revenue: $123,750.",
            affected_entities=["buyer-005", "farm-009", "farm-010", "farm-011"],
            created_at="2026-04-01T09:00:00"),
        SupplyChainInsight(
            id="ins-007", insight_type="risk", priority="medium",
            title="Pesticide residue detected in Tacambaro berry harvest",
            description="Quality inspection qi-010 flagged pesticide residue in harvest harv-026 from Berry Paradise Tacambaro. This batch cannot be exported. Investigate contamination source and implement corrective measures.",
            affected_entities=["farm-011", "harv-026", "qi-010"],
            created_at="2026-04-03T08:00:00"),
        SupplyChainInsight(
            id="ins-008", insight_type="optimization", priority="low",
            title="Switch Ario lemon shipments to domestic market",
            description="Current US lemon prices ($1.50/kg) barely cover export logistics costs. Domestic market at $1.20/kg with zero export overhead yields better net margin. Recommend redirecting farm-012 output.",
            affected_entities=["farm-012"],
            created_at="2026-04-01T11:30:00"),
    ]

    # ── Stats ──────────────────────────────────────────────────
    stats = DemoStats(
        total_farms=12,
        total_hectares=450,
        active_shipments=8,
        monthly_export_tons=1200,
        revenue_ytd_usd=4_200_000,
        top_buyers=["Costco Wholesale", "Driscoll's", "Fresh Del Monte",
                     "Aldi Europe", "Walmart Mexico", "Aeon Japan"],
    )

    # ── Persist everything ─────────────────────────────────────
    data = {
        "farms": [f.model_dump() for f in farms],
        "harvests": [h.model_dump() for h in harvests],
        "shipments": [s.model_dump() for s in shipments],
        "buyer_matches": [b.model_dump() for b in buyer_matches],
        "weather_alerts": [w.model_dump() for w in weather_alerts],
        "market_prices": [p.model_dump() for p in market_prices],
        "quality_inspections": [q.model_dump() for q in quality_inspections],
        "export_documents": [d.model_dump() for d in export_documents],
        "insights": [i.model_dump() for i in insights],
        "stats": stats.model_dump(),
    }
    store.save(data)
